# Generated by Django 4.2.24 on 2025-09-08 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_vendorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyCaregiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='caregiver_avatars/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_caregivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
