# Generated by Django 4.2.24 on 2025-09-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_familycaregiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='can_create_five_min_fun',
            field=models.BooleanField(default=False, help_text='Superadmin approval for creating 5-Min Fun'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='can_create_routine',
            field=models.BooleanField(default=False, help_text='Superadmin approval for creating Routines'),
        ),
    ]
