# Generated by Django 4.2.24 on 2025-09-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_iana_timezone_userprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
