# Generated by Django 4.2.24 on 2025-09-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_iana_timezone_userprofile_timezone_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
