# Generated by Django 4.2.24 on 2025-09-07 03:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='event_photos/')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.TextField()),
                ('tickets_available', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags, e.g., fun, educational', max_length=255)),
                ('age_group', models.CharField(choices=[('0-3', '0-3'), ('3-10', '3-10'), ('11+', '11+'), ('caregivers', 'Caregivers')], default='3-10', max_length=20)),
                ('format_type', models.CharField(choices=[('course', 'Course'), ('workshop', 'Workshop'), ('5-min-play', '5-min Plays')], default='workshop', max_length=20)),
                ('place', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=20)),
                ('superpower', models.CharField(choices=[('love', 'Love'), ('connect', 'Connect'), ('serve', 'Serve')], default='connect', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'userprofile__role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
    ]
