# Generated by Django 4.2.24 on 2025-09-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vendorprofile'),
        ('events', '0004_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='kids',
            field=models.ManyToManyField(blank=True, to='users.kidprofile'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='with_caregiver',
            field=models.BooleanField(default=False),
        ),
    ]
