# Generated by Django 4.2.24 on 2025-09-08 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0005_eventregistration_kids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
