# Generated by Django 4.2.24 on 2025-09-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_familycaregiver'),
        ('events', '0006_alter_eventregistration_caregiver_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventregistration',
            unique_together={('event', 'registered_at')},
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='caregivers',
            field=models.ManyToManyField(blank=True, to='users.familycaregiver'),
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='caregiver',
        ),
    ]
