# Generated by Django 4.2.24 on 2025-09-08 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_familycaregiver'),
        ('events', '0007_alter_eventregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverEventCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.familycaregiver')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'unique_together': {('caregiver', 'event', 'date_completed')},
            },
        ),
    ]
