# Generated by Django 4.2.24 on 2025-09-09 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_familycaregiver'),
        ('events', '0008_caregivereventcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caregivereventcompletion',
            name='caregiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_completions', to='users.familycaregiver'),
        ),
        migrations.AlterField(
            model_name='caregivereventcompletion',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_completions', to='events.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='caregivers',
            field=models.ManyToManyField(blank=True, related_name='eventregistrations', to='users.familycaregiver'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='kids',
            field=models.ManyToManyField(blank=True, related_name='eventregistrations', to='users.kidprofile'),
        ),
    ]
