# Generated by Django 4.2.24 on 2025-09-09 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_familycaregiver'),
        ('events', '0009_event_latitude_event_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='KidEventCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kid_completions', to='events.event')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_completions', to='users.kidprofile')),
            ],
            options={
                'unique_together': {('kid', 'event', 'date_completed')},
            },
        ),
    ]
