# Generated by Django 4.2.24 on 2025-09-10 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_familycaregiver'),
        ('events', '0010_alter_event_end_datetime_alter_event_start_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 10, 17, 45, 37, 629164, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 10, 17, 46, 41, 451148, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kideventcompletion',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kid_completions', to='users.kidprofile'),
        ),
    ]
