# Generated by Django 4.2.24 on 2025-09-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_end_datetime_alter_event_start_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('love', 'Love'), ('connect', 'Connect'), ('serve', 'Serve')], max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, help_text='City for filtering', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.CharField(blank=True, help_text='Country for filtering', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='format_type',
            field=models.CharField(choices=[('course', 'Course'), ('workshop', 'Workshop'), ('contest', 'Contest'), ('hangout', 'Hangout')], default='workshop', max_length=20),
        ),
        migrations.RemoveField(
            model_name='event',
            name='superpower',
        ),
        migrations.AddField(
            model_name='event',
            name='superpower',
            field=models.ManyToManyField(blank=True, to='events.superpower'),
        ),
    ]
