# Generated by Django 4.2.24 on 2025-09-14 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_familycaregiver'),
        ('events', '0012_superpower_event_city_event_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiveMinFun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='five_min_fun_photos/')),
                ('instructions', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='five_min_fun_audio/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(limit_choices_to={'userprofile__role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='five_min_funs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KidFiveMinFunCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('five_min_fun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kid_completions', to='events.fiveminfun')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kid_five_min_fun_completions', to='users.kidprofile')),
            ],
            options={
                'unique_together': {('kid', 'five_min_fun', 'date_completed')},
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
        migrations.RemoveField(
            model_name='event',
            name='superpower',
        ),
        migrations.DeleteModel(
            name='Superpower',
        ),
        migrations.AddField(
            model_name='event',
            name='superpower',
            field=models.CharField(choices=[('love', 'Love'), ('connect', 'Connect'), ('serve', 'Serve')], default='connect', max_length=20),
        ),
    ]
