# Generated by Django 4.2.24 on 2025-09-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_fiveminfun_kidfiveminfuncompletion_remove_event_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiveminfun',
            name='age_group',
            field=models.CharField(blank=True, choices=[('0-3', '0-3'), ('3-10', '3-10'), ('11+', '11+'), ('caregivers', 'Caregivers')], default='3-10', max_length=20),
        ),
        migrations.AddField(
            model_name='fiveminfun',
            name='format_type',
            field=models.CharField(blank=True, choices=[('course', 'Course'), ('workshop', 'Workshop'), ('contest', 'Contest'), ('hangout', 'Hangout')], default='workshop', max_length=20),
        ),
        migrations.AddField(
            model_name='fiveminfun',
            name='place',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=20),
        ),
        migrations.AddField(
            model_name='fiveminfun',
            name='superpower',
            field=models.CharField(blank=True, choices=[('love', 'Love'), ('connect', 'Connect'), ('serve', 'Serve')], default='connect', max_length=20),
        ),
        migrations.AddField(
            model_name='fiveminfun',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
