# Generated by Django 4.2.24 on 2025-09-15 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_familycaregiver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0014_fiveminfun_age_group_fiveminfun_format_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='routine_photos/')),
                ('instructions', models.TextField()),
                ('age_group', models.CharField(choices=[('0-3', '0-3'), ('3-10', '3-10'), ('11+', '11+'), ('caregivers', 'Caregivers')], default='3-10', max_length=20)),
                ('format_type', models.CharField(choices=[('course', 'Course'), ('workshop', 'Workshop'), ('contest', 'Contest'), ('hangout', 'Hangout')], default='workshop', max_length=20)),
                ('place', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=20)),
                ('superpower', models.CharField(choices=[('love', 'Love'), ('connect', 'Connect'), ('serve', 'Serve')], default='connect', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('day', models.CharField(blank=True, help_text='For weekly: weekday name (e.g., Monday); for monthly: day number (1-31)', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fiveminfun',
            name='has_routine',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RoutineInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_instances', to='users.kidprofile')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='events.routine')),
            ],
            options={
                'unique_together': {('routine', 'kid', 'date')},
            },
        ),
        migrations.AddField(
            model_name='routine',
            name='five_min_fun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routines', to='events.fiveminfun'),
        ),
        migrations.AddField(
            model_name='routine',
            name='kids',
            field=models.ManyToManyField(related_name='routines', to='users.kidprofile'),
        ),
        migrations.CreateModel(
            name='KidRoutineCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField(auto_now_add=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kid_routine_completions', to='users.kidprofile')),
                ('routine_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='events.routineinstance')),
            ],
            options={
                'unique_together': {('kid', 'routine_instance')},
            },
        ),
    ]
