# Generated by Django 4.2.24 on 2025-09-15 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_familycaregiver'),
        ('events', '0015_routine_fiveminfun_has_routine_routineinstance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='caregiver',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='day',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='five_min_fun',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='kids',
        ),
        migrations.AddField(
            model_name='routine',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='vendor',
            field=models.ForeignKey(default=1, limit_choices_to={'userprofile__role': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='KidRoutineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('day', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kid_routine_assignments', to=settings.AUTH_USER_MODEL)),
                ('five_min_fun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.fiveminfun')),
                ('kids', models.ManyToManyField(related_name='routine_assignments', to='users.kidprofile')),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.routine')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='routineinstance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='routineinstance',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='events.kidroutineassignment'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='routineinstance',
            unique_together={('assignment', 'kid', 'date')},
        ),
        migrations.RemoveField(
            model_name='routineinstance',
            name='routine',
        ),
    ]
