# Generated by Django 4.2.24 on 2025-09-16 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_remove_routine_caregiver_remove_routine_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidroutineassignment',
            name='five_min_fun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routine_assignments', to='events.fiveminfun'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='age_group',
            field=models.CharField(choices=[('3-10', '3-10'), ('caregivers', 'Caregivers')], default='3-10', max_length=20),
        ),
        migrations.AlterField(
            model_name='routine',
            name='format_type',
            field=models.CharField(choices=[('workshop', 'Workshop'), ('5-min-play', '5-Min Play')], default='workshop', max_length=20),
        ),
        migrations.AlterField(
            model_name='routine',
            name='superpower',
            field=models.CharField(choices=[('connect', 'Connect'), ('create', 'Create')], default='connect', max_length=20),
        ),
    ]
