# Generated by Django 4.2.24 on 2025-09-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_familycaregiver'),
        ('events', '0017_alter_kidroutineassignment_five_min_fun_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kidroutineassignment',
            name='kids',
        ),
        migrations.AddField(
            model_name='kidroutineassignment',
            name='kid',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='routine_assignments', to='users.kidprofile'),
            preserve_default=False,
        ),
    ]
