# Generated by Django 4.2.24 on 2025-09-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_kidroutineassignment_kids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiveminfun',
            name='has_routine',
        ),
        migrations.AddField(
            model_name='fiveminfun',
            name='routines',
            field=models.ManyToManyField(blank=True, related_name='assigned_five_min_funs', to='events.routine'),
        ),
    ]
