# Generated by Django 4.2.24 on 2025-09-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_remove_fiveminfun_has_routine_fiveminfun_routines'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='event',
            name='format_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='superpower',
        ),
        migrations.RemoveField(
            model_name='fiveminfun',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='fiveminfun',
            name='format_type',
        ),
        migrations.RemoveField(
            model_name='fiveminfun',
            name='superpower',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='format_type',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='superpower',
        ),
        migrations.AlterField(
            model_name='fiveminfun',
            name='place',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='age_groups',
            field=models.ManyToManyField(blank=True, to='events.agegroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='format_types',
            field=models.ManyToManyField(blank=True, to='events.formattype'),
        ),
        migrations.AddField(
            model_name='event',
            name='super_powers',
            field=models.ManyToManyField(blank=True, to='events.superpower'),
        ),
        migrations.AddField(
            model_name='fiveminfun',
            name='age_groups',
            field=models.ManyToManyField(blank=True, to='events.agegroup'),
        ),
        migrations.AddField(
            model_name='fiveminfun',
            name='format_types',
            field=models.ManyToManyField(blank=True, to='events.formattype'),
        ),
        migrations.AddField(
            model_name='fiveminfun',
            name='super_powers',
            field=models.ManyToManyField(blank=True, to='events.superpower'),
        ),
        migrations.AddField(
            model_name='routine',
            name='age_groups',
            field=models.ManyToManyField(blank=True, to='events.agegroup'),
        ),
        migrations.AddField(
            model_name='routine',
            name='format_types',
            field=models.ManyToManyField(blank=True, to='events.formattype'),
        ),
        migrations.AddField(
            model_name='routine',
            name='super_powers',
            field=models.ManyToManyField(blank=True, to='events.superpower'),
        ),
    ]
