# Generated by Django 4.2.24 on 2025-09-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_agegroup_formattype_superpower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='format_types',
        ),
        migrations.RemoveField(
            model_name='fiveminfun',
            name='format_types',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='format_types',
        ),
        migrations.AddField(
            model_name='event',
            name='format_type',
            field=models.CharField(choices=[('hangout', 'Hangout'), ('project', 'Project'), ('course', 'Course'), ('workshop', 'Workshop'), ('contest', 'Contest'), ('others', 'Others')], default='workshop', max_length=20),
        ),
        migrations.AddField(
            model_name='fiveminfun',
            name='format_type',
            field=models.CharField(blank=True, choices=[('hangout', 'Hangout'), ('project', 'Project'), ('course', 'Course'), ('workshop', 'Workshop'), ('contest', 'Contest'), ('others', 'Others')], default='workshop', max_length=20),
        ),
        migrations.AddField(
            model_name='routine',
            name='format_type',
            field=models.CharField(choices=[('hangout', 'Hangout'), ('project', 'Project'), ('course', 'Course'), ('workshop', 'Workshop'), ('contest', 'Contest'), ('others', 'Others')], default='workshop', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiveminfun',
            name='place',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], default='indoor', max_length=20),
        ),
        migrations.DeleteModel(
            name='FormatType',
        ),
    ]
