# Generated by Django 4.2.24 on 2025-09-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_remove_event_format_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format_type',
            field=models.CharField(choices=[('hangout', 'Hangout'), ('project', 'Project'), ('course', 'Course'), ('workshop', 'Workshop'), ('contest', 'Contest'), ('others', 'Others'), ('5-min-play', '5-Min Play')], default='workshop', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiveminfun',
            name='format_type',
            field=models.CharField(blank=True, choices=[('hangout', 'Hangout'), ('project', 'Project'), ('course', 'Course'), ('workshop', 'Workshop'), ('contest', 'Contest'), ('others', 'Others'), ('5-min-play', '5-Min Play')], default='workshop', max_length=20),
        ),
        migrations.AlterField(
            model_name='routine',
            name='format_type',
            field=models.CharField(choices=[('hangout', 'Hangout'), ('project', 'Project'), ('course', 'Course'), ('workshop', 'Workshop'), ('contest', 'Contest'), ('others', 'Others'), ('5-min-play', '5-Min Play')], default='workshop', max_length=20),
        ),
    ]
