# Generated by Django 4.2.24 on 2025-09-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_event_format_type_alter_fiveminfun_format_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
