# Generated by Django 4.2.24 on 2025-09-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
    ]
