# Generated by Django 4.2.24 on 2025-09-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiveminfun',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
