# Generated by Django 4.2.24 on 2025-09-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_course_level_roadmappoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiveminfun',
            name='audio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
