# Generated by Django 4.2.24 on 2025-09-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_event_created_at_alter_event_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidroutinecompletion',
            name='date_completed',
            field=models.DateField(),
        ),
    ]
